import Head from 'next/head'
import MeetupList from '@/components/meetups/MeetupList';
import { Inter } from 'next/font/google'
import Layout from '@/components/layout/Layout';



const inter = Inter({ subsets: ['latin'] })

const dummyMeetups=[
  {
    id: 'm1',
    title: 'The First Meetup',
    address: 'City-abc',
    description: 'This is the first Meetup'
  },
  {
    id: 'm2',
    title: 'The Second meetup',
    address: 'City-abc',
    description: 'This is the Second Meetup'
  },
  {
    id: 'm3',
    title: 'The Third meetup',
    address: 'City-abc',
    description: 'This is the Third Meetup'
  }
]

export default function Home(props) {
 
  return (
    <>
      <Head>
        <title>Meet-Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     
      <MeetupList meetups={props.meetups} />
     
       
      </main>
    </>
  )
}

export async function getStaticProps(){
  return{
    props: {
      meetups: dummyMeetups
    }
  }
}
